version: '3'
services:

  app:
    build:
        context: .
    container_name: take-over-app 
    ports:
        - "8000:80"
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: take-over-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TO_DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/opt/db/data
